### ISSUE TITLE
[Improvement] Add support for Box-Cox transformations

### ISSUE THREAD

**Issue by andrewjho** [slfan2013/WCMC_DA#2]
The [Box-Cox transformation](https://www.rdocumentation.org/packages/caret/versions/6.0-73/topics/BoxCoxTrans) is a generalization of the logarithm and power transformations for normalization of data (it requires the estimation of a parameter; see link). In practice I find that it works a little better than applying a log transform or arbitrarily testing various power transformations prior to analysis.

**Comment by slfan2013** [comment]
Yes, Box-Cox transformation is very useful when trying to transform a variable to a normal distribution. However, Box-Cox has at least one parameter (`λ`) to be determined by the data. For (untargeted) metabolomics data set, if we use Box-Cox, each compound will have its own `λ`, making compounds no longer at a "same scale", which makes interpretation on a pathway level very difficult. I think it is too "data-massaging". I would suggest selecting ONE transformation, e.g. log10 or log2 or natual log or squre root, to applly to all of the compound.

**Comment by andrewjho** [comment]
That's a good point!
